%define		kdeappsver	18.12.0
%define		qtver		5.9.0
%define		kaname		kalarm
Summary:	kalarm
Name:		ka5-%{kaname}
Version:	18.12.0
Release:	1
License:	GPL v2+/LGPL v2.1+
Group:		X11/Applications
Source0:	http://download.kde.org/stable/applications/%{kdeappsver}/src/%{kaname}-%{version}.tar.xz
# Source0-md5:	fa87bc9e006d2717463d24147d6fcbe0
URL:		http://www.kde.org/
BuildRequires:	Qt5Core-devel >= %{qtver}
BuildRequires:	cmake >= 2.8.12
BuildRequires:	ka5-akonadi-devel >= 18.04.0
BuildRequires:	ka5-kalarmcal-devel >= %{kdeappsver}
BuildRequires:	ka5-kimap-devel >= %{kdeappsver}
BuildRequires:	ka5-mailcommon-devel >= %{kdeappsver}
BuildRequires:	kf5-extra-cmake-modules >= 5.44.0
BuildRequires:	kf5-kauth-devel >= 5.44.0
BuildRequires:	kf5-kcmutils-devel >= 5.44.0
BuildRequires:	kf5-kcodecs-devel >= 5.44.0
BuildRequires:	kf5-kcompletion-devel >= 5.44.0
BuildRequires:	kf5-kconfigwidgets-devel >= 5.44.0
BuildRequires:	kf5-kdbusaddons-devel >= 5.44.0
BuildRequires:	kf5-kdelibs4support-devel >= 5.44.0
BuildRequires:	kf5-kholidays-devel >= 5.44.0
BuildRequires:	kf5-kiconthemes-devel >= 5.44.0
BuildRequires:	kf5-kjobwidgets-devel >= 5.44.0
BuildRequires:	qt5-build >= %{qtver}
BuildRequires:	rpmbuild(macros) >= 1.164
BuildRequires:	shared-mime-info
BuildRequires:	tar >= 1:1.22
BuildRequires:	xz
BuildRoot:	%{tmpdir}/%{name}-%{version}-root-%(id -u -n)

%description
KAlarm is a personal alarm message, command and email scheduler.

Features

• Display alarms using your own text message, the text generated by a
command, or a text or image file. • Audible alarm using a sound file •
Recurring alarm on an hours/minutes, daily, weekly, monthly or annual
basis, or set it to trigger every time you log in. • Display alarms
color and font customization • Support for multiple alarm calendars,
which for example enables you to share alarms between a laptop and
desktop computer.

%prep
%setup -q -n %{kaname}-%{version}

%build
install -d build
cd build
%cmake \
	-DKDE_INSTALL_USE_QT_SYS_PATHS=ON \
	..
%{__make}

%install
rm -rf $RPM_BUILD_ROOT
%{__make} -C build install \
	DESTDIR=$RPM_BUILD_ROOT

%find_lang %{kaname} --all-name --with-kde

%clean
rm -rf $RPM_BUILD_ROOT

%files -f %{kaname}.lang
%defattr(644,root,root,755)
/etc/dbus-1/system.d/org.kde.kalarm.rtcwake.conf
/etc/xdg/autostart/kalarm.autostart.desktop
/etc/xdg/kalarm.categories
/etc/xdg/kalarm.renamecategories
%attr(755,root,root) %{_bindir}/kalarm
%attr(755,root,root) %{_bindir}/kalarmautostart
%{_prefix}/libexec/kauth/kalarm_helper
%{_desktopdir}/org.kde.kalarm.desktop
%{_datadir}/config.kcfg/kalarmconfig.kcfg
%{_datadir}/dbus-1/interfaces/org.kde.kalarm.kalarm.xml
%{_datadir}/dbus-1/system-services/org.kde.kalarm.rtcwake.service
%{_iconsdir}/hicolor/128x128/apps/kalarm.png
%{_iconsdir}/hicolor/16x16/apps/kalarm.png
%{_iconsdir}/hicolor/22x22/apps/kalarm.png
%{_iconsdir}/hicolor/32x32/apps/kalarm.png
%{_iconsdir}/hicolor/48x48/apps/kalarm.png
%{_iconsdir}/hicolor/64x64/apps/kalarm.png
%{_datadir}/kalarm
%{_datadir}/kconf_update/kalarm-1.2.1-general.pl
%{_datadir}/kconf_update/kalarm-1.9.5-defaults.pl
%{_datadir}/kconf_update/kalarm-15.08-kickoff.sh
%{_datadir}/kconf_update/kalarm-2.0.2-general.pl
%{_datadir}/kconf_update/kalarm-2.1.5-general.pl
%{_datadir}/kconf_update/kalarm-version.pl
%{_datadir}/kconf_update/kalarm.upd
%dir %{_datadir}/kxmlgui5/kalarm
%{_datadir}/kxmlgui5/kalarm/kalarmui.rc
%{_datadir}/metainfo/org.kde.kalarm.appdata.xml
%{_datadir}/polkit-1/actions/org.kde.kalarm.rtcwake.policy
